### ISSUE TITLE
[question] font used in screen shots?

### ISSUE THREAD

**Issue by damnskippy** [orta/vscode-themes#2]
Just wondering what the font used in the screenshots for the theme is?
Thanks.

**Comment by damnskippy** [comment]
Looks like Firacode perhaps.

**Comment by orta** [comment]
It is 👍🏻

**Comment by damnskippy** [comment]
Thanks for confirming - and thanks for all the screencaps.
Might be helpful to add the font info to Readme for anyone else that may be curious about this too.
